### ISSUE TITLE
Using libgdx tile APIs instead of developing new ones

### ISSUE THREAD

**Issue by oopsurdead** [Ameliorate/Buildstation-3#31]
libgdx already comes with a pretty decent maps API, that can integrate with the rendering engine and other parts of the library. You can even use existing graphical map editors with it to make maps.

https://github.com/libgdx/libgdx/wiki/Tile-maps

Is there any reason you're developing your own APIs for this purpose?

**Comment by Ameliorate** [comment]
I didn't know about this beforehand, but this doesn't seem to fulfill my needs as I want to be able to separate rendering the actual tiles, lighting, line of sight, right clicking, and other things. Also I've been thinking up a map structure that wouldn't be compatible with this and would abstract the current barrier between client and server.

**Comment by oopsurdead** [comment]
Ah, that makes sense. Regardless, it might be a good idea to extend the existing classes rather than reinventing the wheel, both to cut down on work and so you can make use of things like Tiled to edit maps.
