### ISSUE TITLE
Networking Library

### ISSUE THREAD

**Issue by oopsurdead** [Ameliorate/Buildstation-3#32]
I've noticed that you're writing your own networking code using JSON objects. That's probably going to introduce some overhead and be rather cumbersome to write, you might want to consider using a library like Kryonet (https://github.com/EsotericSoftware/kryonet) which is fast and pretty simple.

**Comment by Ameliorate** [comment]
This may be a concern later, but I'd rather get a working game rather than get a game that sends a whole 16*16 of tiles in 8 bytes in 2020. Although I will be willing to do some unnecessary things for expandability or major performance boosts.

**Comment by captkirk88** [comment]
You will find that @oopsurdead is right.  I have used Kryonet and although it has its kinks like no channels, it will do.  You should put it in as soon as possible then build tests and improve upon networking before building your networking framework and then having to go back to implement kryonet.

**Comment by Ameliorate** [comment]
I have been thinking of doing unit tests, but as the game wasn't designed with unit tests in mind, it would likely be a slow process.

**Comment by Ameliorate** [comment]
Okay this library is great. Sorry for the criticism earlier. The entirety of most packet sorters (Now called listeners) can be reduced to a few lines.
